# Saint-Cloud and the two racecourses, by their real coordinates.
#
# Step 7 of docs/PARIS_1901.md. Reads tools/.cache/stcloud.json, which
# tools/fetch_stcloud.py pulls from OpenStreetMap by name.
#
# Everything here replaces a hand-typed half-frame coordinate in world.js. See
# fetch_stcloud.py for what each of them was standing on instead.
import io
import json
import math
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ORIGIN = (48.85826, 2.29450)
ORIGIN_XZ = (520.0, 300.0)
MLAT = 111320.0
MLON = 111320.0 * math.cos(math.radians(ORIGIN[0]))


def xz(lat, lon):
    return (ORIGIN_XZ[0] + (lon - ORIGIN[1]) * MLON,
            ORIGIN_XZ[1] - (lat - ORIGIN[0]) * MLAT)


d = json.load(io.open(os.path.join(ROOT, 'tools', '.cache', 'stcloud.json'),
                      encoding='utf-8'))
# …and the two parks the book keeps landing him in.
_r = os.path.join(ROOT, 'tools', '.cache', 'rothschild.json')
if os.path.exists(_r):
    d['elements'] += json.load(io.open(_r, encoding='utf-8'))['elements']

# Collect every node of every element that carries a given name, in game metres,
# keeping only what falls inside the world's frame — the Avre aqueduct runs
# ninety kilometres out to the Eure and most of it is nowhere near Paris.
X0, X1, Z0, Z1 = -5100, 6100, -3800, 2500


def gather(pred):
    pts = []
    for e in d['elements']:
        if not pred(e.get('tags', {})):
            continue
        g = e.get('geometry') or []
        for m in e.get('members', []):
            g = g + (m.get('geometry') or [])
        if not g and 'lat' in e:
            g = [{'lat': e['lat'], 'lon': e['lon']}]
        for p in g:
            q = xz(p['lat'], p['lon'])
            if X0 <= q[0] <= X1 and Z0 <= q[1] <= Z1:
                pts.append(q)
    return pts


def box(pts):
    xs = [p[0] for p in pts]
    zs = [p[1] for p in pts]
    return (sum(xs) / len(xs), sum(zs) / len(zs),
            (max(xs) - min(xs)) / 2, (max(zs) - min(zs)) / 2)


def named(n):
    return lambda t: t.get('name', '') == n


def has(sub):
    """OSM writes 'Parc de Boulogne - Edmond de Rothschild' with a dash that is
    not always the dash you typed. Match on the part that is unambiguous."""
    return lambda t: sub in t.get('name', '')


out = {}
for key, pred, label in [
        ('PONT', named('Pont de Saint-Cloud'), 'the Pont de Saint-Cloud'),
        ('AVRE', named("Passerelle de l'Avre"), "the Avre aqueduct's crossing"),
        ('CHURCH', named('Église Saint-Clodoald'), 'the village church'),
        ('PARK', named('Parc de Saint-Cloud'), 'the park of Saint-Cloud'),
        ('LONGCHAMP', named('Hippodrome de Longchamp'), 'Longchamps racecourse'),
        ('AUTEUIL', named("Hippodrome d'Auteuil"), 'the Auteuil racecourse'),
        # "standing in my basket at the top of the tallest chestnut, the
        # propeller touching the ground" — M. Edmond de Rothschild's park,
        # 13 July 1901, where Princess Isabel sent his lunch up into the tree
        # and a medal of St. Benedict followed by post (Ch. XVIII; scenario VII).
        ('ROTHSCHILD', has('Rothschild'),
         "Edmond de Rothschild's park — the tallest chestnut"),
        # where the kite-flying boys caught the No. 1's guide rope and ran
        # AGAINST the wind to break her fall (Ch. XI)
        ('BAGATELLE', named('Parc de Bagatelle'), 'the park of Bagatelle')]:
    pts = gather(pred)
    if not pts:
        print('!! nothing for %s' % label)
        continue
    cx, cz, rx, rz = box(pts)
    out[key] = (round(cx, 1), round(cz, 1), round(rx, 1), round(rz, 1), label)
    print('%-10s %-28s centre (%7.1f,%7.1f)  half-extent %6.1f x %6.1f  (%d nodes)'
          % (key, label, cx, cz, rx, rz, len(pts)))

js = '''// Saint-Cloud, the Avre aqueduct and the two racecourses — real coordinates.
//
// GENERATED by tools/gen_stcloud.py from OpenStreetMap, by name. Step 7 of
// docs/PARIS_1901.md, and the answer to bug reports #31 and #32.
//
// Every one of these replaces a coordinate typed by hand into the world's OLD
// HALF FRAME. That frame's conversion (world.js H2) is still correct; the
// ground under it stopped being. When the world was re-surveyed the aerodrome
// moved to the Aéro-Club's true position and the Seine moved to
// OpenStreetMap's, and the scenery stayed where it was:
//
//   the Avre aqueduct        564 m from any water, NINE metres from the centre
//                            of Longchamps racecourse
//   the Pont de Saint-Cloud  636 m from any water
//   Deutsch's air-ship shed  3.9 km from the aerodrome it stands beside
//   the village church       187 m from the river
//
// A rigid translation could not have saved it either: the layout was wrong
// inside itself, putting the bridge 612 m EAST of the village where the real
// one is 469 m west.
//
// `x, z` is the centre; `rx, rz` the half-extent, so an ellipse or a box can be
// built from either without re-deriving anything.
'''
for k, (cx, cz, rx, rz, label) in out.items():
    js += "\nexport const %s = { x: %s, z: %s, rx: %s, rz: %s };  // %s\n" \
          % (k, cx, cz, rx, rz, label)

js += '''
// The racecourses were drawn as 520 x 300 and 420 x 260 ellipses typed by hand.
// Longchamp's real ground is TALLER THAN IT IS WIDE — 340 by 698 — so the game
// had it turned through ninety degrees, which is why the western two thirds of
// the track fell outside every exclusion that was supposed to keep buildings
// off it.
'''
io.open(os.path.join(ROOT, 'src', 'paris_stcloud.js'), 'w',
        encoding='utf-8', newline='\n').write(js)
print('\nwrote src/paris_stcloud.js')
