# The real footprint of every Paris landmark, as a rectangle the world can build to.
#
# The audit (tools/audit_landmarks.py) found twelve of eighteen monuments wrong:
# hand-built from period pictures and never turned to face their own street.
# Guessing them one at a time is how they got that way, so this reduces each
# real outline to the four numbers a builder actually needs and writes them out
# for src/world.js to read:
#
#   x, z   the centre of the footprint, in game coordinates
#   len    its long side, and the bearing of that side
#   wid    its short side
#   ry     three.js rotation.y that turns a box's local +X along the long side
#
# The rectangle is the SMALLEST-AREA one that contains the outline (rotating
# callipers over the convex hull), not an axis-aligned box — a building sits at
# whatever angle its street does, and an axis-aligned box round a diagonal one
# is half again too fat. This is the same rule tools/fetch_paris_buildings.py
# already uses for the twelve thousand ordinary houses; the monuments simply
# never got it.
#
# Use: python tools/gen_paris_footprints.py
import json
import math
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
CACHE = os.path.join(HERE, 'osm_landmarks.json')
OUT = os.path.join(ROOT, 'src', 'paris_footprints.js')

ORIGIN = (48.85826, 2.29450)
OXZ = (520.0, 300.0)
M_LAT = 111320.0
M_LON = 111320.0 * math.cos(math.radians(ORIGIN[0]))


def geo(lat, lon):
    return (OXZ[0] + (lon - ORIGIN[1]) * M_LON,
            OXZ[1] - (lat - ORIGIN[0]) * M_LAT)


def rings(gj):
    t = gj.get('type')
    if t == 'Polygon':
        return [gj['coordinates'][0]]
    if t == 'MultiPolygon':
        return [poly[0] for poly in gj['coordinates']]
    if t == 'LineString':
        return [gj['coordinates']]
    if t == 'Point':
        return [[gj['coordinates']]]
    return []


def hull(pts):
    pts = sorted(set(pts))
    if len(pts) < 3:
        return pts

    def half(ps):
        out = []
        for p in ps:
            while len(out) >= 2:
                (ax, az), (bx, bz) = out[-2], out[-1]
                if (bx - ax) * (p[1] - az) - (bz - az) * (p[0] - ax) <= 0:
                    out.pop()
                else:
                    break
            out.append(p)
        return out
    lower = half(pts)
    upper = half(list(reversed(pts)))
    return lower[:-1] + upper[:-1]


def min_area_box(pts):
    """Smallest-area rectangle round the points: centre, long, short, angle."""
    h = hull(pts)
    if len(h) < 3:
        cx = sum(p[0] for p in pts) / len(pts)
        cz = sum(p[1] for p in pts) / len(pts)
        return cx, cz, 0.0, 0.0, 0.0
    best = None
    for i in range(len(h)):
        ax, az = h[i]
        bx, bz = h[(i + 1) % len(h)]
        ang = math.atan2(bz - az, bx - ax)
        c, s = math.cos(-ang), math.sin(-ang)
        us = [(p[0] * c - p[1] * s, p[0] * s + p[1] * c) for p in h]
        u0 = min(u for u, v in us)
        u1 = max(u for u, v in us)
        v0 = min(v for u, v in us)
        v1 = max(v for u, v in us)
        area = (u1 - u0) * (v1 - v0)
        if best is None or area < best[0]:
            cu, cv = (u0 + u1) / 2, (v0 + v1) / 2
            cb, sb = math.cos(ang), math.sin(ang)
            best = (area, cu * cb - cv * sb, cu * sb + cv * cb,
                    u1 - u0, v1 - v0, ang)
    _, cx, cz, du, dv, ang = best
    if dv > du:                       # keep the long side first
        du, dv = dv, du
        ang += math.pi / 2
    return cx, cz, du, dv, ang


def main():
    cache = json.load(open(CACHE, encoding='utf8'))
    rows = []
    for pid in sorted(cache):
        gj = cache[pid].get('geojson')
        if not gj:
            continue
        pts = [geo(c[1], c[0]) for r in rings(gj) for c in r]
        if len(pts) < 3:
            continue
        cx, cz, ln, wd, ang = min_area_box(pts)
        # ang is the long side's direction as atan2(dz, dx). A three.js box has
        # its long side on local +X, and rotation.y = t sends +X to
        # (cos t, 0, -sin t) — so the rotation that lays it along the side is -ang.
        rows.append((pid, cx, cz, ln, wd, -ang, cache[pid].get('osm', '?')))
    with open(OUT, 'w', encoding='utf8') as f:
        f.write('// The real footprint of each Paris landmark — GENERATED by\n')
        f.write('// tools/gen_paris_footprints.py from OpenStreetMap outlines.\n')
        f.write('//\n')
        f.write('// The smallest-area rectangle round the real outline: where it stands, how\n')
        f.write('// long and how wide it is, and the three.js rotation.y that lays a box along\n')
        f.write('// it. Twelve of the eighteen monuments were hand-built from period pictures\n')
        f.write('// and never turned to face their own street — the Hotel de Ville was 60\n')
        f.write('// degrees out at exactly the right size, the Invalides was 349 m of building\n')
        f.write('// drawn as a 65 m dome. Anything placed by eye can be placed by this instead.\n')
        f.write('//\n')
        f.write('// { x, z, len, wid, ry } — metres and radians, in game coordinates.\n')
        f.write('export const FOOTPRINTS = {\n')
        for pid, cx, cz, ln, wd, ry, osm in rows:
            f.write('  %-12s { x: %8.1f, z: %8.1f, len: %6.1f, wid: %6.1f, ry: %7.4f },  // %s\n'
                    % (pid + ':', cx, cz, ln, wd, ry, osm))
        f.write('};\n\n')
        f.write('/** The footprint of a landmark, or null. */\n')
        f.write('export function footprint(id) { return FOOTPRINTS[id] || null; }\n')
    print('wrote %s with %d footprints' % (os.path.relpath(OUT, ROOT), len(rows)))
    for pid, cx, cz, ln, wd, ry, osm in rows:
        print('  %-12s %6.0f x %-5.0f m  at (%.0f, %.0f)  ry %+.3f' % (pid, ln, wd, cx, cz, ry))


if __name__ == '__main__':
    main()
