// The real footprint of each monaco landmark — GENERATED by
// tools/city_footprints.py from OpenStreetMap outlines.
//
// The smallest-area rectangle round the real outline: where it stands, how
// long and how wide it is, and the three.js rotation.y that lays a box along
// it. Anything placed by eye can be placed by this instead.
//
// { x, z, len, wid, ry } — metres and radians, in game coordinates.
export const FOOTPRINTS = {
  rock:          { x:    -77.2, z:    272.4, len:  108.8, wid:  102.6, ry: -2.3383 },  // relation/393226
  oceano:        { x:    360.5, z:    345.0, len:  102.5, wid:   29.4, ry: -2.4755 },  // way/23715051
                 // begun 1899, still building in 1902
  casino:        { x:    610.7, z:   -618.7, len:  162.8, wid:   59.2, ry: -2.2161 },  // way/161769674
                 // the Casino and the Salle Garnier are ONE building — the opera is built onto its sea front
  opera:         { x:    610.7, z:   -618.7, len:  162.8, wid:   59.2, ry: -2.2161 },  // way/161769674
                 // the Salle Garnier, on the Casino’s sea front — the same outline
  cathedral:     { x:    133.2, z:    385.0, len:   77.2, wid:   39.9, ry: -1.7520 },  // way/362871296
                 // finished 1903, so a year off in 1902
  fortantoine:   { x:    559.1, z:     79.8, len:   29.0, wid:   21.1, ry:  2.6659 },  // way/573030549
  stedevote:     { x:     -7.7, z:   -416.1, len:   31.6, wid:   14.1, ry:  2.4769 },  // way/94399398
};

/** The footprint of a landmark, or null. */
export function footprint(id) { return FOOTPRINTS[id] || null; }
