// The real footprint of each Paris landmark — GENERATED by
// tools/gen_paris_footprints.py from OpenStreetMap outlines.
//
// The smallest-area rectangle round the real outline: where it stands, how
// long and how wide it is, and the three.js rotation.y that lays a box along
// it. Twelve of the eighteen monuments were hand-built from period pictures
// and never turned to face their own street — the Hotel de Ville was 60
// degrees out at exactly the right size, the Invalides was 349 m of building
// drawn as a 65 m dome. Anything placed by eye can be placed by this instead.
//
// { x, z, len, wid, ry } — metres and radians, in game coordinates.
export const FOOTPRINTS = {
  bastille:    { x:   5986.6, z:    867.0, len:   18.0, wid:   18.0, ry: -0.0548 },  // way/227757683
  ecolemil:    { x:   1272.7, z:   1000.5, len:  469.5, wid:  269.0, ry: -2.3388 },  // way/106312008
  eiffel:      { x:    519.9, z:    299.9, len:  123.6, wid:  123.6, ry: -0.7721 },  // way/5013364
  etoile:      { x:    559.6, z:  -1427.5, len:   50.4, wid:   28.1, ry:  1.1285 },  // way/226413508
  gareorsay:   { x:   2863.8, z:    111.7, len:  188.5, wid:   77.5, ry:  2.7209 },  // way/63178753
  grandpalais: { x:   1821.7, z:   -578.2, len:  240.0, wid:  159.0, ry: -1.5591 },  // way/56185523
  hoteldeville: { x:   4770.2, z:    504.1, len:  144.3, wid:   89.3, ry: -1.9188 },  // relation/284089
  invalides:   { x:   1847.0, z:    555.1, len:  273.3, wid:  256.1, ry:  3.0692 },  // relation/1463538
  louvre:      { x:   3563.5, z:     -5.2, len:  565.5, wid:  303.0, ry:  2.7724 },  // relation/7515426
  madeleine:   { x:   2714.7, z:  -1010.0, len:  128.5, wid:   43.3, ry: -2.0173 },  // way/54180046
  montmartre:  { x:   4073.4, z:  -2876.6, len:   96.0, wid:   50.4, ry:  1.6482 },  // way/23762981
  notredame:   { x:   4572.7, z:    896.9, len:  135.6, wid:   79.3, ry: -0.4640 },  // way/201611261
  opera:       { x:   3245.0, z:  -1233.8, len:  148.8, wid:  100.8, ry: -4.4354 },  // way/54667456
  pantheon:    { x:   4297.9, z:   1642.2, len:  112.2, wid:   85.0, ry: -0.3182 },  // way/16407465
  petitpalais: { x:   2018.2, z:   -564.1, len:  130.4, wid:   89.4, ry: -1.6547 },  // relation/2778854
  republique:  { x:   5597.0, z:   -728.6, len:   14.8, wid:   13.4, ry:  0.8314 },  // way/227150549
  trocadero:   { x:     76.6, z:   -131.7, len:  427.4, wid:  131.6, ry: -2.3405 },  // relation/6826569
  vendome:     { x:   3078.9, z:   -725.6, len:    6.5, wid:    6.4, ry:  2.5737 },  // way/227762241
};

/** The footprint of a landmark, or null. */
export function footprint(id) { return FOOTPRINTS[id] || null; }
