// Saint-Cloud, the Avre aqueduct and the two racecourses — real coordinates.
//
// GENERATED by tools/gen_stcloud.py from OpenStreetMap, by name. Step 7 of
// docs/PARIS_1901.md, and the answer to bug reports #31 and #32.
//
// Every one of these replaces a coordinate typed by hand into the world's OLD
// HALF FRAME. That frame's conversion (world.js H2) is still correct; the
// ground under it stopped being. When the world was re-surveyed the aerodrome
// moved to the Aéro-Club's true position and the Seine moved to
// OpenStreetMap's, and the scenery stayed where it was:
//
//   the Avre aqueduct        564 m from any water, NINE metres from the centre
//                            of Longchamps racecourse
//   the Pont de Saint-Cloud  636 m from any water
//   Deutsch's air-ship shed  3.9 km from the aerodrome it stands beside
//   the village church       187 m from the river
//
// A rigid translation could not have saved it either: the layout was wrong
// inside itself, putting the bridge 612 m EAST of the village where the real
// one is 469 m west.
//
// `x, z` is the centre; `rx, rz` the half-extent, so an ellipse or a box can be
// built from either without re-deriving anything.

export const PONT = { x: -4671.0, z: 2188.3, rx: 98.1, rz: 34.5 };  // the Pont de Saint-Cloud

export const AVRE = { x: -4672.4, z: 896.3, rx: 222.0, rz: 19.2 };  // the Avre aqueduct's crossing

export const CHURCH = { x: -4990.6, z: 1956.1, rx: 29.3, rz: 16.2 };  // the village church

export const PARK = { x: -4785.5, z: 2015.7, rx: 58.3, rz: 90.9 };  // the park of Saint-Cloud

export const LONGCHAMP = { x: -3964.4, z: 368.3, rx: 418.2, rz: 704.7 };  // Longchamps racecourse

export const AUTEUIL = { x: -2242.0, z: 780.9, rx: 345.9, rz: 539.7 };  // the Auteuil racecourse

export const ROTHSCHILD = { x: -4214.5, z: 1210.1, rx: 274.4, rz: 298.4 };  // Edmond de Rothschild's park — the tallest chestnut

export const BAGATELLE = { x: -2923.1, z: -1054.7, rx: 378.1, rz: 571.9 };  // the park of Bagatelle

// The racecourses were drawn as 520 x 300 and 420 x 260 ellipses typed by hand.
// Longchamp's real ground is TALLER THAN IT IS WIDE — 340 by 698 — so the game
// had it turned through ninety degrees, which is why the western two thirds of
// the track fell outside every exclusion that was supposed to keep buildings
// off it.
