// The landmarks of Paris, 1901 — step 5 of docs/PARIS_1901.md.
//
// GENERATED by tools/gen_paris_landmarks.py. See docs/PARIS_LANDMARKS.md for
// what each of these was in 1901 and where its figures come from.
//
// paris_geo.PLACES named twenty-seven landmarks and world.js modelled sixteen.
// A coordinate is not a building, so the rest stood as nothing at all.
//
// `src` is the honest half of this file:
//   'measured'  the footprint OpenStreetMap holds, reduced to its smallest-area
//               oriented box — and for these the outline is the 1901 outline,
//               because they are all still standing on the same ground.
//   'published' a figure from the record, where the fetch would not give a
//               usable outline: the Louvre and the Hôtel de Ville are mapped as
//               courtyards and wings rather than as one building, the Petit
//               Palais sits in the Grand Palais's shadow, and Lachambre's
//               balloon works at Vaugirard was never surveyed at all.
//
// `w` is across the building and `l` along it; `ry` is a three.js rotation.y.
export const LANDMARKS = [
  { id: 'bastille', x: 5986.6, z: 867.0, w: 18.0, l: 18.0, ry: -1.6256, h: 47, kind: 'column',
    src: 'measured' },   // the July Column, 1840, on the site of the Bastille
  { id: 'chatelet', x: 4311.0, z: 352.2, w: 91.5, l: 45.7, ry: -1.9545, h: 26, kind: 'theatre',
    src: 'measured' },   // the 1862 theatre on the place
  { id: 'gareorsay', x: 2860.9, z: 89.5, w: 220.7, l: 94.1, ry: 1.1683, h: 32, kind: 'station',
    src: 'measured' },   // the Gare d'Orsay, opened 28 May 1900 — a barrel-vaulted train hall behind a hotel front
  { id: 'grandpalais', x: 1821.7, z: -578.2, w: 159.0, l: 240.0, ry: -1.559, h: 44, kind: 'palace',
    src: 'measured' },   // already modelled — kept here as a control
  { id: 'hoteldeville', x: 4747, z: 488, w: 85, l: 110, ry: -0.3491, h: 48, kind: 'palace',
    src: 'published' },   // rebuilt 1873–1892 after the fire of 1871
  { id: 'louvre', x: 3661, z: -1, w: 190, l: 420, ry: -0.384, h: 30, kind: 'palace',
    src: 'published' },   // open at the west end: the Tuileries were demolished in 1883
  { id: 'madeleine', x: 2714.7, z: -1010.0, w: 43.3, l: 128.5, ry: -2.0173, h: 30, kind: 'temple',
    src: 'measured' },   // the Napoleonic temple, 1842 — 52 Corinthian columns all round
  { id: 'petitpalais', x: 2002, z: -565, w: 90, l: 130, ry: -0.4363, h: 24, kind: 'palace',
    src: 'published' },   // 1900 Exposition work, a year old in 1901
  { id: 'republique', x: 5608.2, z: -732.2, w: 65.5, l: 224.8, ry: -0.7341, h: 0, kind: 'square',
    src: 'measured' },   // the place, with Morice’s bronze Republic of 1883 at its centre
  { id: 'vaugirard', x: 1180, z: 2170, w: 34, l: 62, ry: -0.2094, h: 14, kind: 'works',
    src: 'published' },   // Lachambre's balloon works, where his envelopes were made
  { id: 'vendome', x: 3078.9, z: -725.6, w: 6.4, l: 6.5, ry: 2.5737, h: 44, kind: 'column',
    src: 'measured' },   // the 1810 column; toppled by the Commune 1871, re-erected 1875
];
