// The Thiers fortifications, 1841–1919 — the wall Paris was inside.
//
// GENERATED by tools/gen_paris_wall.py. Step 4 of docs/PARIS_1901.md.
//
// A continuous bastioned rampart about 33 km round, with a ditch, a cleared
// glacis outside on which building was forbidden, and the rue Militaire inside.
// It was not pulled down until 1919–29, so it stood through every flight in
// this game, and an airship at a hundred and fifty metres had it in view as the
// definite edge of the city. Without it Paris simply thinned out into
// countryside.
//
// Traced off the Boulevard Périphérique, laid in 1973 along the line of the
// demolished wall — the one alignment the period street screen drops by name as
// an anachronism is the one that records where the 1901 wall stood.
//
// NOT off the commune boundary, which is the obvious source and follows the
// wall everywhere except round the two Bois: they were annexed in 1859 and lie
// OUTSIDE the enceinte, so the boundary runs along the far edge of the wood
// instead. The Bois de Boulogne is the western side, which is the side inside
// this map.
//
// 5.6 km in 2 runs — the arc of the ring that falls inside the survey's
// frame. Only a sixth of the wall is in frame at all: the world is centred on
// the Tower and reaches west to Saint-Cloud, so eastern Paris is off the map.
//
// Heights are the real thing: the rampart stood about 10 m over the glacis with
// a 3 m parapet, the ditch was some 15 m wide, and the glacis was cleared for
// 250 m — the zone non aedificandi, which is why the ring reads as a green belt
// in every period photograph.
export const WALL_RUNS = [
  [[883.7,-3317.8],[1009.1,-3436.9],[1098.8,-3524.7],[1159.7,-3572.4],[1219.8,-3621.5],[1289.6,-3687.2],[1383.2,-3775.5]],
  [[-2116.4,442.3],[-2056.9,385.5],[-1993,334],[-1907.6,276.2],[-1853.4,234.8],[-1804.9,183.4],[-1768.9,132.1],[-1740.5,73.4],[-1717.6,11.9],[-1654.9,-147.8],[-1623.5,-215.4],[-1588.6,-268.8],[-1498,-371.3],[-1451.9,-435.6],[-1413.6,-504.3],[-1387.3,-561.4],[-1349.7,-649.7],[-1319.8,-715.3],[-1284.8,-782.5],[-1233.6,-868.2],[-1183.4,-940.2],[-1118.7,-1023.6],[-1059.6,-1104.1],[-941.5,-1309.1],[-901.5,-1380.1],[-867,-1441.9],[-830.8,-1503.2],[-788.5,-1572.5],[-748.2,-1620.4],[-699.6,-1665.2],[-604.5,-1755],[-542.5,-1823.7],[-507.5,-1876.8],[-476.5,-1932.8],[-447.4,-1995],[-423.3,-2064.2],[-397.2,-2165.3],[-374.2,-2229.4],[-324.2,-2340.5],[-288.8,-2410.1],[-241.8,-2475],[-164.5,-2554.3],[-90.7,-2622.3],[-0.8,-2704.9],[65.6,-2767.5],[300.5,-2988],[360.2,-3032.7],[434,-3070.5],[603.9,-3125.7],[682.7,-3163.1],[750.5,-3208.4],[820.5,-3259.2],[883.7,-3317.8]],
];

export const WALL = { rampart: 10, parapet: 3, ditch: 15, glacis: 250, base: 34 };
