// The Thiers fortifications, 1841–1919 — the wall Paris was inside.
//
// GENERATED by tools/gen_paris_wall.py. Step 4 of docs/PARIS_1901.md.
//
// A continuous bastioned rampart about 33 km round, with a ditch, a cleared
// glacis outside on which building was forbidden, and the rue Militaire inside.
// It was not pulled down until 1919–29, so it stood through every flight in
// this game, and an airship at a hundred and fifty metres had it in view as the
// definite edge of the city. Without it Paris simply thinned out into
// countryside.
//
// Traced off the Boulevard Périphérique, laid in 1973 along the line of the
// demolished wall — the one alignment the period street screen drops by name as
// an anachronism is the one that records where the 1901 wall stood.
//
// NOT off the commune boundary, which is the obvious source and follows the
// wall everywhere except round the two Bois: they were annexed in 1859 and lie
// OUTSIDE the enceinte, so the boundary runs along the far edge of the wood
// instead. The Bois de Boulogne is the western side, which is the side inside
// this map.
//
// 7.9 km in 2 runs — the arc of the ring that falls inside the survey's
// frame. Only a sixth of the wall is in frame at all: the world is centred on
// the Tower and reaches west to Saint-Cloud, so eastern Paris is off the map.
//
// Heights are the real thing: the rampart stood about 10 m over the glacis with
// a 3 m parapet, the ditch was some 15 m wide, and the glacis was cleared for
// 250 m — the zone non aedificandi, which is why the ring reads as a green belt
// in every period photograph.
export const WALL_RUNS = [
  [[-1992.9,323.5],[-1907.6,269.2],[-1844.4,215.9],[-1794.9,163.2],[-1761.9,110.8],[-1739.8,58.3],[-1717.3,6.2],[-1702.9,-46],[-1654.9,-148.4],[-1633.3,-199.3],[-1601.3,-248.8],[-1574,-298.4],[-1488.1,-392.5],[-1451.3,-439.4],[-1425.2,-487.3],[-1401.4,-535.2],[-1383.7,-583.9],[-1363,-631.8],[-1333.5,-678],[-1317.7,-726.3],[-1296.3,-773.5],[-1271.9,-819.8],[-1234.7,-863],[-1208.2,-908.2],[-1180.4,-952.9],[-1149.2,-996.3],[-1114.9,-1038.7],[-1080.2,-1080.5],[-1049.6,-1123],[-1025.2,-1166.9],[-945.7,-1295.6],[-900.6,-1382.7],[-873,-1424.4],[-828.1,-1510.7],[-805,-1553.4],[-773.8,-1593],[-736.8,-1630],[-699.1,-1666.3],[-659.3,-1701.3],[-613.6,-1733.5],[-583.5,-1771.7],[-549.4,-1808],[-500.6,-1888.5],[-478.1,-1929.5],[-457.3,-1971.3],[-440,-2014.8],[-425.5,-2059.8],[-412.9,-2105.8],[-403.3,-2153.7],[-388.2,-2198.9],[-369.6,-2242.3],[-331,-2328.7],[-310.3,-2371.1],[-287.4,-2412.4],[-262.3,-2452.3],[-232.8,-2489.5],[-200.4,-2524.8],[-163,-2556.6],[-129.5,-2590.8],[-91.2,-2621.5],[-55.9,-2653.9],[10.6,-2721.1],[81.3,-2784.5],[288.6,-2973.5],[321.8,-3005.5],[360.3,-3032.9],[397,-3061.6],[443.6,-3081.4],[490.5,-3100.4],[600.5,-3122],[639.2,-3146.9],[684.6,-3165.1],[758.7,-3216.6],[830.8,-3269.3],[895.7,-3329.1],[1024.1,-3450.2],[1055.6,-3481.2],[1085.9,-3513.7],[1155.1,-3568.7],[1189.8,-3596],[1223.6,-3624.5],[1287.9,-3685.9],[1384.7,-3778.6]],
  [[-2409,2517.3],[-2425.5,2457.5],[-2434.7,2395.5],[-2443,2333.5],[-2446.1,2270.1],[-2433.5,2202.7],[-2427.5,2137.6],[-2431.2,2012.5],[-2385.1,1938.9],[-2369.1,1873.4],[-2362.7,1810.4],[-2368.5,1750.3],[-2370.4,1689.5],[-2375.6,1629.6],[-2392.4,1571.8],[-2422.2,1516.2],[-2489.4,1405.1],[-2525.4,1349.2],[-2547.8,1291],[-2566.2,1232.1],[-2575.6,1171.8],[-2574.1,1110.4],[-2572.5,1049.1],[-2559.7,986.8],[-2538.6,924.3],[-2511,861.6],[-2462.3,798.2],[-2430.9,736.7],[-2341.5,673],[-2116.5,436],[-2057,379.2]],
];

export const WALL = { rampart: 10, parapet: 3, ditch: 15, glacis: 250, base: 34 };
