// St. Louis, 1904 — the frame of the Louisiana Purchase Exposition.
//
// GENERATED by tools/gen_stlouis_geo.py. Do not edit by hand; edit the
// generator, which carries the whole method and its error bars.
//
// This is step 3 of docs/STLOUIS_PLAT.md. Unlike Paris and Monaco, none of it
// comes from a live data feed: the fair was staff and plaster and it was pulled
// down in 1905, so the geometry is georeferenced off the fair's own published
// ground plan (Buxton & Skinner, 1904) and its own published dimensions
// (docs/STLOUIS_PALACES.md), tied to the earth by the two things it built that
// are still standing — the Palace of Fine Arts, now the Saint Louis Art Museum,
// and the Smithsonian's flight cage, now in the zoo.
//
// HOW GOOD IS IT
//   scale        2.750 m per sheet pixel, from Machinery's published
//                1,000 x 525 ft against its measured 110.2 x 58.0 px, and
//                confirmed by the Concourse's fourteen acres (14.49) and
//                by the guide's "two miles from E. to W." (1.97)
//   axis         from the fan's own mirror symmetry, six estimates agreeing to
//                about a degree. Education and Electricity, which are mirror
//                images, come out sharing an x to 1.1 m.
//   bearing      the two surviving controls subtend the same angle on the sheet
//                and on the earth to under two degrees
//   residual     23.3 m at the flight cage, 743 m from the anchor
//
// THE FRAME. +x runs UP the grand axis, from the Grand Basin toward Festival
// Hall and the museum behind it; +z is ninety degrees clockwise from that,
// which is the same relation Paris and Monaco have between east and south. The
// origin is the centre of the Grand Basin, because that is what the fair itself
// was composed around: "As all the buildings and avenues of the Exposition
// radiate from this feature."
export const ORIGIN = { lat: 38.642515, lon: -90.291585 };
export const BEARING_X = 217.054;      // degrees true, of the game's +x

const M_PER_DEG_LAT = 111132.0;
const M_PER_DEG_LON = 111320.0 * Math.cos(ORIGIN.lat * Math.PI / 180);
const _bx = BEARING_X * Math.PI / 180, _bz = (BEARING_X + 90) * Math.PI / 180;

/** A latitude and longitude, in game metres. */
export function geo(lat, lon) {
  const e = (lon - ORIGIN.lon) * M_PER_DEG_LON;
  const n = (lat - ORIGIN.lat) * M_PER_DEG_LAT;
  return { x: e * Math.sin(_bx) + n * Math.cos(_bx),
           z: e * Math.sin(_bz) + n * Math.cos(_bz) };
}

/** …and back, for anyone checking the world against a modern map. */
export function latlon(x, z) {
  const e = x * Math.sin(_bx) + z * Math.sin(_bz);
  const n = x * Math.cos(_bx) + z * Math.cos(_bz);
  return { lat: ORIGIN.lat + n / M_PER_DEG_LAT, lon: ORIGIN.lon + e / M_PER_DEG_LON };
}

/**
 * Every place on the fairground, in game metres, traced off the 1904 plat.
 * The palaces are segmented centroids; the rest were read off gridded crops
 * and are good to about eight metres.
 */
export const PLACES = {
  agriculture:        { x:    813.9, z:    844.6, name: 'Palace of Agriculture' },
  basin_head:         { x:    187.5, z:    -29.5, name: 'the head of the Grand Basin' },
  colonnade_e:        { x:    278.0, z:    169.3, name: 'Colonnade of States, east kiosk' },
  colonnade_w:        { x:    270.9, z:   -208.6, name: 'Colonnade of States, west kiosk' },
  concourse:          { x:    349.4, z:   1735.4, name: 'the Aeronautic Concourse' },
  education:          { x:    -33.2, z:   -195.5, name: 'Palace of Education and Social Economy' },
  electricity:        { x:    -34.3, z:    184.6, name: 'Palace of Electricity' },
  festival_hall:      { x:    315.6, z:    -11.8, name: 'Festival Hall' },
  fine_arts:          { x:    417.9, z:     -8.5, name: 'Palace of Fine Arts' },
  fine_arts_e:        { x:    450.2, z:     89.5, name: 'Fine Arts, east wing' },
  fine_arts_w:        { x:    449.7, z:   -106.6, name: 'Fine Arts, west wing' },
  forestry:           { x:    422.7, z:   1219.8, name: 'Palace of Forestry, Fish and Game' },
  grand_basin:        { x:      0.0, z:      0.0, name: 'the Grand Basin' },
  horticulture:       { x:   1160.1, z:    633.7, name: 'Palace of Horticulture' },
  liberal_arts:       { x:   -101.4, z:   -597.9, name: 'Palace of Liberal Arts' },
  machinery:          { x:    103.8, z:    467.3, name: 'Palace of Machinery' },
  manufactures:       { x:   -278.9, z:   -265.2, name: 'Palace of Manufactures' },
  mines:              { x:    122.9, z:   -464.5, name: 'Palace of Mines and Metallurgy' },
  observation_wheel:  { x:    426.2, z:    729.1, name: 'the Observation Wheel' },
  pike_east:          { x:   -713.2, z:    -45.3, name: 'the Pike, Lindell end' },
  pike_west:          { x:    -98.0, z:   1009.4, name: 'the Pike, Skinker end' },
  purchase_monument:  { x:   -281.1, z:     -7.0, name: 'the Louisiana Purchase Monument' },
  steam_gas_fuels:    { x:    227.3, z:    704.7, name: 'Steam, Gas and Fuels Building' },
  transportation:     { x:    -61.1, z:    648.5, name: 'Palace of Transportation' },
  us_government:      { x:    158.9, z:   -761.3, name: 'United States Government Building' },
  varied_industries:  { x:   -283.3, z:    251.2, name: 'Palace of Varied Industries' },
};

export function place(id) {
  const p = PLACES[id];
  if (!p) throw new Error('no such place at the Exposition: ' + id);
  return { x: p.x, z: p.z, name: p.name };
}

/**
 * Art Hill, as a function rather than a cone.
 *
 * Measured off the terrain tiles along the fair's grand axis (STLOUIS_PLAT.md):
 * the ground climbs 12.1 m from the Grand Basin and then goes genuinely level,
 * which is why Festival Hall and the museum could stand on it at all. The
 * commonly quoted figure for Art Hill is sixty feet, and the difference from
 * the measured twelve is the basin's water against the ground at its lip plus
 * the museum's own terracing; sixteen sits inside that band.
 *
 * The DEM takes 267 m to make that climb. THE FAIR DID NOT: the toe here is the
 * water's edge at x = 190 and the crown is the Terrace of States at x = 270,
 * because the fair cut the slope into a stepped cascade face eighty metres long
 * rather than a hillside. That is not a contradiction of the DEM — the DEM is
 * today's ground, regraded after 1905 — and it is checked against the fair's
 * own plumbing: sixteen metres of face plus the twenty-four feet the water is
 * thrown above the terrace is about seventy-five feet, against the ninety the
 * guide says the pumps had to lift it.
 *
 * In this frame the climb is exactly the +x axis, which is what the axis was
 * chosen to be, so the hill is a ridge across the head of the basin rather than
 * a cone dropped on the plain: the palaces down the fan stay on the level.
 *
 * The crown is flat ACROSS the fan as well as along it, out to the ends of the
 * Colonnade of States, because the Terrace of States was a terrace: the fourteen
 * states sat in a level arc and the two kiosks at its ends stood at the same
 * height as Festival Hall between them. Then it falls away to the level of the
 * palaces, which is why Mines and Machinery — the innermost pair of the fan —
 * come out within half a metre of zero.
 */
export const HILL = { h: 16, toe: 190, crown: 270, flat: 250, halfWidth: 520 };

const smooth = (t) => (t <= 0 ? 0 : t >= 1 ? 1 : t * t * (3 - 2 * t));

export function groundAt(x, z) {
  const up = smooth((x - HILL.toe) / (HILL.crown - HILL.toe));
  const out = smooth((Math.abs(z) - HILL.flat) / (HILL.halfWidth - HILL.flat));
  return HILL.h * up * (1 - out);
}
