// The footprints of the Louisiana Purchase Exposition, 1904.
//
// GENERATED by tools/gen_stlouis_geo.py. Step 4 of docs/STLOUIS_PLAT.md.
//
// Position and rotation are traced off the fair's own ground plan; WIDTH AND
// LENGTH ARE NOT. They are the fair's published dimensions from the Official
// Guide (docs/STLOUIS_PALACES.md, every figure cited to a line), because the
// draughtsman's pink wash stops inside the colonnades and under-reads a palace
// by a few per cent. So the plan says where and which way round, and the
// record says how big — which is the right way round for both of them.
//
// `w` is across the building and `l` along its long axis, in metres. `rot` is a
// three.js rotation.y that puts the local +x on the long axis.
export const SITES = [
  { id: 'education', x:    -33.2, z:   -195.5, w:  160.0, l:  228.6, rot:  -1.8706 },
  { id: 'electricity', x:    -34.3, z:    184.6, w:  160.0, l:  228.6, rot:  -1.2969 },
  { id: 'mines', x:    122.9, z:   -464.5, w:  160.0, l:  228.6, rot:  -2.1350 },
  { id: 'liberal_arts', x:   -101.4, z:   -597.9, w:  160.0, l:  228.6, rot:  -2.1352 },
  { id: 'manufactures', x:   -278.9, z:   -265.2, w:  160.0, l:  365.8, rot:  -1.8756 },
  { id: 'varied_industries', x:   -283.3, z:    251.2, w:  160.0, l:  381.0, rot:  -1.3347 },
  { id: 'machinery', x:    103.8, z:    467.3, w:  160.0, l:  304.8, rot:  -1.2400 },
  { id: 'transportation', x:    -61.1, z:    648.5, w:  160.0, l:  396.2, rot:  -1.0482 },
  { id: 'agriculture', x:    813.9, z:    844.6, w:  160.0, l:  487.7, rot:  -2.5999 },
  { id: 'steam_gas_fuels', x:    227.3, z:    704.7, w:   91.4, l:  100.6, rot:  -3.0822 },
  { id: 'us_government', x:    158.9, z:   -761.3, w:   53.3, l:  220.7, rot:   2.6069 },
  { id: 'fine_arts', x:    417.9, z:     -8.5, w:   50.6, l:  106.1, rot:  -1.5801 },
  { id: 'fine_arts_w', x:    449.7, z:   -106.6, w:   62.2, l:  128.6, rot:  -3.1090 },
  { id: 'fine_arts_e', x:    450.2, z:     89.5, w:   62.2, l:  128.6, rot:   3.1167 },
  { id: 'horticulture', x:   1160.1, z:    633.7, w:  121.9, l:  121.9, rot:  -1.0635 },
  { id: 'forestry', x:    422.7, z:   1219.8, w:   86.3, l:  163.7, rot:   2.1247 },
];

export const SITE = Object.fromEntries(SITES.map((s) => [s.id, s]));

/** The Pike, as the plat draws it: one straight mile of concessions. The
 *  guide's "one and one-half miles … turning sharply to the south" counts the
 *  leg down University Way that this sheet draws as a separate plaza. */
export const PIKE = { from: 'pike_east', to: 'pike_west', width: 78 };

/** The Aeronautic Concourse: the fenced field the airship contest flew from.
 *  374 x 157 m off the plat, which is 14.49 acres against the
 *  fourteen the record gives — the closest thing to a scale check the sheet
 *  contains. The paling round it was thirty feet high (docs/STLOUIS_PALACES). */
export const CONCOURSE = { w: 374, d: 157, fence: 9.14 };

/** The Grand Basin: "semi-circular in shape and 600 feet in diameter." */
export const BASIN = { r: 91.4 };
